language: php

before_script:
  - composer self-update
  - php app/console doctrine:database:create --env=test
  - sh scripts/composer_install.sh
  - sh scripts/update_schema.sh
  - sh scripts/assetic_install.sh
  - sh scripts/cache_clear.sh

script:
  - phpunit -c app

notifications:
  email:
    -  llopez@sopinet.com