# application tasks to be customized and to run after the main provision

- args:
    chdir: /var/www/
  name: install dependencies
  shell: composer install -n --no-progress

- args:
    chdir: /var/www/
  name: doctrine schema update
  shell: php app/console -n doctrine:schema:update --force
