imports:
- resource: parameters.yml
- resource: services.yml
- resource: common/imports.php

framework:
  csrf_protection: null
  default_locale: '%locale%'
  form: null
  fragments: null
  http_method_override: true
  router:
    resource: '%kernel.root_dir%/config/routing.yml'
    strict_requirements: null
  secret: '%secret%'
  session:
    handler_id: null
  templating:
    engines:
    - twig
  translator:
    fallback: '%locale%'
  trusted_hosts: null
  trusted_proxies: null
  validation:
    enable_annotations: true

# Twig Configuration
twig:
  debug: '%kernel.debug%'
  form:
    resources:
    - bootstrap_3_layout.html.twig
  strict_variables: '%kernel.debug%'

# Assetic Configuration
assetic:
  bundles:
  - AppBundle
  debug: '%kernel.debug%'
  filters:
    cssrewrite: null
  use_controller: false

# Doctrine Configuration
doctrine:
  dbal:
    charset: UTF8
    dbname: '%database_name%'
    driver: '%database_driver%'
    host: '%database_host%'
    password: '%database_password%'
    port: '%database_port%'
    types:
      json: Sonata\Doctrine\Types\JsonType
    user: '%database_user%'
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
  host: '%mailer_host%'
  password: '%mailer_password%'
  spool:
    type: memory
  transport: '%mailer_transport%'
  username: '%mailer_user%'

# Security Configuration
security:
  access_control:
  - path: ^/login$
    role: IS_AUTHENTICATED_ANONYMOUSLY
  - path: ^/register
    role: IS_AUTHENTICATED_ANONYMOUSLY
  - path: ^/resetting
    role: IS_AUTHENTICATED_ANONYMOUSLY
  - path: ^/_wdt
    role: IS_AUTHENTICATED_ANONYMOUSLY
  - path: ^/_profiler
    role: IS_AUTHENTICATED_ANONYMOUSLY
  - path: ^/login$
    role: IS_AUTHENTICATED_ANONYMOUSLY
  - path: ^/admin/login$
    role: IS_AUTHENTICATED_ANONYMOUSLY
  - path: ^/admin/logout$
    role: IS_AUTHENTICATED_ANONYMOUSLY
  - path: ^/admin/login-check$
    role: IS_AUTHENTICATED_ANONYMOUSLY
  - path: ^/admin
    role: ROLE_ADMIN
  access_decision_manager:
    strategy: unanimous
  encoders:
    FOS\UserBundle\Model\UserInterface: sha512
  firewalls:
    admin:
      anonymous: true
      form_login:
        check_path: /admin/login_check
        failure_path: null
        login_path: /admin/login
        provider: fos_userbundle
        use_forward: false
      logout:
        path: /admin/logout
      pattern: /admin(.*)
    main:
      anonymous: null
      form_login:
        check_path: /login_check
        csrf_provider: form.csrf_provider
        failure_path: null
        login_path: /login
        provider: fos_userbundle
        use_forward: false
      logout:
        path: /logout
      oauth:
        default_target_path: /
        failure_path: /login
        login_path: /login
        oauth_user_provider:
          service: sopinet_user_provider
        resource_owners:
          facebook: /login/check-facebook
          google: /login/check-google
      pattern: ^/
      switch_user: true
  providers:
    fos_userbundle:
      id: fos_user.user_provider.username_email
  role_hierarchy:
    ROLE_ADMIN:
    - ROLE_USER
    - ROLE_SONATA_ADMIN
    ROLE_SUPER_ADMIN:
    - ROLE_ADMIN
    - ROLE_ALLOWED_TO_SWITCH
    SONATA:
    - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT
