imports:
- resource: config_dev.yml

framework:
  profiler:
    collect: false
  session:
    storage_id: session.storage.mock_file
  test: null

web_profiler:
  intercept_redirects: false
  toolbar: false

swiftmailer:
  disable_delivery: true
