app:
  resource: '@AppBundle/Controller/'
  type: annotation

hwi_oauth_redirect:
  prefix: /connect
  resource: '@HWIOAuthBundle/Resources/config/routing/redirect.xml'

hwi_oauth_login:
  prefix: /login
  resource: '@HWIOAuthBundle/Resources/config/routing/login.xml'

facebook_login:
  pattern: /login/check-facebook

google_login:
  pattern: /login/check-google

# Sonata Admin
admin:
  prefix: /admin
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'

_sonata_admin:
  prefix: /admin
  resource: .
  type: sonata_admin
# END Sonata Admin

# SonataUser
sonata_user:
  prefix: /admin
  resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'

sonata_user_security:
  resource: '@SonataUserBundle/Resources/config/routing/sonata_security_1.xml'

sonata_user_resetting:
  prefix: /resetting
  resource: '@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml'

sonata_user_profile:
  prefix: /profile
  resource: '@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml'

sonata_user_register:
  prefix: /register
  resource: '@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml'

sonata_user_change_password:
  prefix: /profile
  resource: '@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml'
# END SonataUser

NelmioApiDocBundle:
  prefix: /api/doc
  resource: '@NelmioApiDocBundle/Resources/config/routing.yml'
