# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  apihelper:
    arguments:
    - '@doctrine'
    - '@fos_rest.view_handler'
    class: AppBundle\Services\ApiHelper

  app.login_success_handler:
    arguments:
    - '@service_container'
    - '@router'
    class: AppBundle\Authentication\CheckUser
    tags:
    - channel: security
      name: monolog.logger

  sopinet_user_provider:
    arguments:
    - '@fos_user.user_manager'
    - facebook: facebookUid
      google: gplusUid
    class: AppBundle\Security\Core\User\FOSUBUserProvider
