FOS\UserBundle\Model\User:
  properties:
    password:
        exclude: true
    salt:
        exclude: true
    username:
      expose: true
      groups: [user, profile, resume]
    email:
      expose: true
      groups: [user, profile, resume]