sonata_user:
  admin:
    group:
      class: Application\Sonata\UserBundle\Admin\GroupAdmin
    user:
      class: Application\Sonata\UserBundle\Admin\UserAdmin
  class:
    group: Application\Sonata\UserBundle\Entity\Group
    user: Application\Sonata\UserBundle\Entity\User
  manager_type: orm
  security_acl: false
