- apt_repository: repo=ppa:ondrej/{{ php.ppa }}
  name: add ppa repository
  sudo: true

- apt: update_cache=yes
  name: update apt
  sudo: true

- apt: pkg=php5 state=latest
  name: install php5
  sudo: true

- apt: pkg=php5-fpm state=latest
  name: install php5-fpm
  sudo: true

- apt: pkg={{ item }} state=latest
  name: install PHP packages
  sudo: true
  when: php.packages is defined
  with_items: php.packages

- include: configure.yml
- include: pecl.yml
