- apt: pkg="php5-dev" state=present
  name: install
  when: php.pecl_packages is defined

- changed_when: '''already installed'' not in pecl_result.stdout'
  failed_when: pecl_result.stderr or ('ERROR' in pecl_result.stdout)
  name: install package
  register: pecl_result
  shell: echo "\n\n\n\n\n\n\n\n\n" | pecl install {{ item }}
  when: php.pecl_packages is defined
  with_items: php.pecl_packages

- name: create extension .ini file
  template: >
    src="extension.tpl"
    dest="/etc/php5/mods-available/{{ item }}.ini"
    owner="root"
    group="root"
    mode=0644
  with_items: php.pecl_packages
  when: php.pecl_packages is defined

- name: enable extension
  shell: php5enmod {{ item }}
  when: php.pecl_packages is defined
  with_items: php.pecl_packages
